<a href="https://colab.research.google.com/github/Akshatpattiwar512/Letsupgrade-Advance-Data-Science/blob/main/ADV_DATA_SCIENCE_DAY_4_ASSIGNMENT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Eigenvalues and Eigenvectors of an array

Explaination

In [193]:
#Eigenvectors are unit vectors, which means that their length or magnitude is equal to 1.0.
#They are often referred as right vectors, which simply means a column vector (as opposed to a row vector or a left vector).
#A right-vector is a vector as we understand them.

#Eigenvalues are coefficients applied to eigenvectors that give the vectors their length or magnitude. 


Syntax

In [194]:
#Syntax: numpy.linalg.eig()

Code

In [195]:
# importing numpy library 
import numpy as np 
  
# create numpy 2d-array 
m = np.array([[1, 2], 
              [2, 3]]) 
  
print("Printing the Original square array:\n", 
      m) 
  
# finding eigenvalues and eigenvectors 
w, v = np.linalg.eig(m) 
  
# printing eigen values 
print("Printing the Eigen values of the given square array:\n", w) 
  
# printing eigen vectors 
print("Printing Right eigenvectors of the given square array:\n",v)

Printing the Original square array:
 [[1 2]
 [2 3]]
Printing the Eigen values of the given square array:
 [-0.23606798  4.23606798]
Printing Right eigenvectors of the given square array:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


### digitize()

Explanation

In [196]:
#With the help of np.digitize() method, we can get the indices of the bins to which the each value is belongs to an array by using np.digitize() method

Syntax

In [197]:
#Syntax : np.digitize(Array, Bin, Right)


Code

In [198]:
# import numpy 
import numpy as np 
  
a = np.array([1.2, 2.4, 3.6, 4.8]) 
bins = np.array([1.0, 1.3, 2.5, 4.0, 10.0]) 
  
# using np.digitize() method 
gfg = np.digitize(a, bins) 
  
print(gfg) 

[1 2 3 4]


### repeat()

Explaination

In [199]:
#The repeat() function is used to repeat elements of a Series. 
#Returns a new Series where each element of the current Series is repeated consecutively a given number of times.
#The number of repetitions for each element. This should be a non-negative integer.

Syntax

In [200]:
#Syntax: Series.repeat(repeats, axis=None)

Code

In [201]:
# importing pandas as pd 
import pandas as pd 
  
# Creating the Series 
sr = pd.Series([10, 25, 3, 11, 24, 6]) 
  
# Create the Index 
index_ = ['Coca Cola', 'Sprite', 'Coke', 'Fanta', 'Dew', 'ThumbsUp'] 
  
# set the index 
sr.index = index_ 
  
# Print the series 
print(sr) 

Coca Cola    10
Sprite       25
Coke          3
Fanta        11
Dew          24
ThumbsUp      6
dtype: int64


### squeeze()

Explaination

In [202]:
#Pandas Series.squeeze() function squeeze 1 dimensional axis objects into scalars.
#Series or DataFrames with a single element are squeezed to a scalar.
#DataFrames with a single column or a single row are squeezed to a Series. Otherwise the object is unchanged.

Syntax

In [203]:
#Syntax: Series.squeeze(axis=None)

Code

In [204]:
# importing pandas as pd 
import pandas as pd 
  
# Creating the Series 
sr = pd.Series([100, 25, 32, 118, 24, 65]) 
  
# Print the series 
print(sr)

0    100
1     25
2     32
3    118
4     24
5     65
dtype: int64


### linspace()

Explaination

In [205]:
#The numpy.linspace() function returns number spaces evenly w.r.t interval

Syntax

In [206]:
#numpy.linspace(start,
#               stop,
#               num = 50,
#               endpoint = True,
#               retstep = False,
#               dtype = None)

Code

In [207]:
import numpy as np 
  
# restep set to True 
print("B\n", np.linspace(2.0, 3.0, num=5, retstep=True), "\n") 
  
# To evaluate sin() in long range  
x = np.linspace(0, 2, 10) 
print("A\n", np.sin(x)) 

B
 (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25) 

A
 [0.         0.22039774 0.42995636 0.6183698  0.77637192 0.8961922
 0.9719379  0.99988386 0.9786557  0.90929743]


### clip()

Explaination

In [208]:
#Pandas dataframe.clip() is used to trim values at specified input threshold.
#We can use this function to put a lower limit and upper limit on the values that any cell can have in the dataframe.

Syntax

In [209]:
#Syntax: DataFrame.clip(lower=None, upper=None, axis=None, inplace=False, *args, **kwargs)

Code

In [210]:
# importing pandas as pd 
import pandas as pd 
  
# Creating a dataframe using dictionary 
df = pd.DataFrame({"A":[-5, 8, 12, -9, 5, 3], 
                   "B":[-1, -4, 6, 4, 11, 3], 
                   "C":[11, 4, -8, 7, 3, -2]}) 
  
# Printing the data frame for visualization 
df 

A   B   C
0  -5  -1  11
1   8  -4   4
2  12   6  -8
3  -9   4   7
4   5  11   3
5   3   3  -2

### extract()

Explaination

In [211]:
#Series.str can be used to access the values of the series as strings and apply several methods to it.
#Pandas Series.str.extract() function is used to extract capture groups in the regex pat as columns in a DataFrame.
#For each subject string in the Series, extract groups from the first match of regular expression pat.

Syntax

In [212]:
#Syntax: Series.str.extract(pat, flags=0, expand=True)

Code

In [213]:
# importing pandas as pd 
import pandas as pd 
  
# importing re for regular expressions 
import re 
  
# Creating the Series 
sr = pd.Series(['New_York', 'Lisbon', 'Tokyo', 'Paris', 'Munich']) 
  
# Creating the index 
idx = ['City 1', 'City 2', 'City 3', 'City 4', 'City 5'] 
  
# set the index 
sr.index = idx 
  
# Print the series 
print(sr) 

City 1    New_York
City 2      Lisbon
City 3       Tokyo
City 4       Paris
City 5      Munich
dtype: object


### argpartition()

Explaination

In [214]:
#numpy.argpartition() function is used to create a indirect partitioned copy of input array with its elements rearranged in such a way that the value of the element in k-th position is in the position it would be in a sorted array.
#All elements smaller than the k-th element are moved before this element and all equal or greater are moved behind it.
#The ordering of the elements in the two partitions is undefined.
#It returns an array of indices of the same shape as arr, i.e arr[index_array] yields a partition of arr.

Syntax

In [215]:
#Syntax : numpy.argpartition(arr, kth, axis=-1, kind=’introselect’, order=None)

Code

In [216]:
import numpy as geek 
  
# input array 
in_arr = geek.array([[ 2, 0,  1], [ 5, 4, 9] ]) 
print ("Input array : \n", in_arr)  
  
out_arr = geek.argpartition(in_arr, 1, axis = 1) 
print ("Output partitioned array indices :\n ", out_arr) 

Input array : 
 [[2 0 1]
 [5 4 9]]
Output partitioned array indices :
  [[1 2 0]
 [1 0 2]]


### setdiff1d()

Explaination

In [217]:
#setdiff1d() function find the set difference of two arrays and return the unique values in arr1 that are not in arr2. 

Syntax

In [218]:
#Syntax : numpy.setdiff1d(arr1, arr2, assume_unique = False)

Code

In [219]:
# importing numpy as np  
import numpy as np  
   
arr1 = [5, 6, 2, 3, 4] 
arr2 = [1, 2, 3] 
   
gfg = np.setdiff1d(arr1, arr2) 
   
print (gfg)

[4 5 6]


### itemsize

Explaination

In [220]:
#Pandas series is a One-dimensional ndarray with axis labels.
#The labels need not be unique but must be a hashable type.
#The object supports both integer- and label-based indexing and provides a host of methods for performing operations involving the index.
#Pandas Series.itemsize attribute return the size of the dtype of the item of the underlying data for the given Series object.

Syntax

In [221]:
#Syntax:Series.itemsize

Code

In [222]:
# importing pandas as pd 
import pandas as pd 
  
# Creating the Series 
sr = pd.Series(['New York', 'Chicago', 'Toronto', 'Lisbon']) 
  
# Creating the row axis labels 
sr.index = ['City 1', 'City 2', 'City 3', 'City 4']  
  
# Print the series 
print(sr)

City 1    New York
City 2     Chicago
City 3     Toronto
City 4      Lisbon
dtype: object


### hstack()

Explaination

In [223]:
#numpy.hstack() function is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array.

Syntax

In [224]:
#Syntax : numpy.hstack(tup)

Code

In [225]:
import numpy as np
  
# input array 
in_arr1 = np.array([ 1, 2, 3] ) 
print ("1st Input array : \n", in_arr1)  
  
in_arr2 = np.array([ 4, 5, 6] ) 
print ("2nd Input array : \n", in_arr2)  
  
# Stacking the two arrays horizontally 
out_arr = np.hstack((in_arr1, in_arr2)) 
print ("Output horizontally stacked array:\n ", out_arr) 

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
  [1 2 3 4 5 6]


### vstack()

Explaination

In [226]:
#numpy.vstack() function is used to stack the sequence of input arrays vertically to make a single array.

Syntax

In [227]:
#Syntax : numpy.vstack(tup)

Code

In [228]:
import numpy as np
  
# input array 
in_arr1 = np.array([ 1, 2, 3] ) 
print ("1st Input array : \n", in_arr1)  
  
in_arr2 = np.array([ 4, 5, 6] ) 
print ("2nd Input array : \n", in_arr2)  
  
# Stacking the two arrays vertically 
out_arr = np.vstack((in_arr1, in_arr2)) 

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]


### hsplit()

Explaination

In [229]:
#split() function is used to split strings around given separator/delimiter.
#The function splits the string in the Series/Index from the beginning, at the specified delimiter string.

Syntax

In [230]:
#Syntax : hsplit(array,column number)[index]

Code

In [231]:
#import numpy as np
import numpy as np
arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
np.hsplit(arr,2)[1]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

### vsplit()

Explaination

In [232]:
#split() function is used to split strings around given separator/delimiter.
#The function splits the string in the Series/Index from the beginning, at the specified delimiter string.

Syntax

In [233]:
#Syntax : hsplit(array,row number)[index]


Code

In [234]:
#import numpy as np
import numpy as np
arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
np.vsplit(arr,3)[2]

array([[ 9, 10, 11, 12]])

### View vs Shallow Copy

Explaination

In [235]:
#View: This is also known as Shallow Copy. The view is just a view of the original array and view does not own the data.
#When we make changes to the view it affects the original array, and when changes are made to the original array it affects the view.

Syntax

In [236]:
#Syntax : arr.view()

Code

In [237]:
import numpy as np 
  
# creating array 
arr = np.array([2, 4, 6, 8, 10]) 
  
# creating view  
v = arr.view() 
  
# both arr and v have different id 
print("id of arr", id(arr)) 
print("id of v", id(v)) 
  
# changing original array 
# will effect view 
arr[0] = 12
  
# printing array and view 
print("original array- ", arr) 
print("view- ", v) 

id of arr 140374131557120
id of v 140374131235696
original array-  [12  4  6  8 10]
view-  [12  4  6  8 10]


### Deep Copy

Explaination

In [238]:
#Copy: This is also known as Deep Copy. The copy is completely a new array and copy owns the data.
#When we make changes to the copy it does not affect the original array, and when changes are made to the original array it does not affect the copy.

Syntax

In [239]:
#Syntax : arr.copy()

Code

In [240]:
import numpy as np 
  
# creating array 
arr = np.array([2, 4, 6, 8, 10]) 
  
# creating copy of array 
c = arr.copy() 
  
# both arr and c have different id 
print("id of arr", id(arr)) 
print("id of c", id(c)) 
  
# changing original array 
# this will not effect copy 
arr[0] = 12
  
# printing array and copy 
print("original array- ", arr) 
print("copy- ", c) 

id of arr 140374131310224
id of c 140374131260272
original array-  [12  4  6  8 10]
copy-  [ 2  4  6  8 10]


### copy()

Explaination

In [241]:
#Returns a shallow copy of a list. 
#hallow copy means the any modification in new list won’t be reflected to original list 

Syntax

In [242]:
#Syntax : list.copy()

Code

In [243]:
lis1 = [ 1, 2, 3, 4 ] 
  
# Using copy() to create a shallow copy 
lis2 = lis1.copy() 
  
# Printing new list  
print ("The new list created is : " + str(lis2)) 
  
# Adding new element to new list 
lis2.append(5) 
  
# Printing lists after adding new element 
# No change in old list 
print ("The new list after adding new element : " + str(lis2)) 
print ("The old list after adding new element to new list  : " + str(lis1)) 

The new list created is : [1, 2, 3, 4]
The new list after adding new element : [1, 2, 3, 4, 5]
The old list after adding new element to new list  : [1, 2, 3, 4]


### meshgrid()

Explaination

In [244]:
#The numpy.meshgrid function is used to create a rectangular grid out of two given one-dimensional arrays representing the Cartesian indexing or Matrix indexing.

Syntax

In [245]:
#Syntax : np.meshgrid(x, y, sparse = True)

Code

In [246]:
import numpy as np 
# from matplotlib import pyplot as plt 
# pyplot imported for plotting graphs 
  
x = np.linspace(-4, 4, 9) 
  
# numpy.linspace creates an array of 
# 9 linearly placed elements between 
# -4 and 4, both inclusive  
y = np.linspace(-5, 5, 11) 
  
# The meshgrid function returns 
# two 2-dimensional arrays  
x_1, y_1 = np.meshgrid(x, y) 
  
print("x_1 = ") 
print(x_1) 
print("y_1 = ") 
print(y_1) 

x_1 = 
[[-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]]
y_1 = 
[[-5. -5. -5. -5. -5. -5. -5. -5. -5.]
 [-4. -4. -4. -4. -4. -4. -4. -4. -4.]
 [-3. -3. -3. -3. -3. -3. -3. -3. -3.]
 [-2. -2. -2. -2. -2. -2. -2. -2. -2.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.]
 [ 4.  4.  4.  4.  4.  4.  4.  4.  4.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.]]


### swapaxes()

Explaination

In [247]:
#With the help of matrix.swapaxes() method, we are able to swap the axes a matrix by using the same method.

Syntax

In [248]:
#Syntax : matrix.swapaxes()

Code

In [249]:
import numpy as np 
             
# make matrix with numpy 
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]') 
             
# applying matrix.swapaxes() method 
matx = gfg.swapaxes(1, 1) 
   
print(matx)

[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]


### column_stack()s

Explaination

In [250]:
#numpy.column_stack() function is used to stack 1-D arrays as columns into a 2-D array.
#It takes a sequence of 1-D arrays and stack them as columns to make a single 2-D array.
#2-D arrays are stacked as-is, just like with hstack function.

Syntax

In [251]:
#Syntax : numpy.column_stack(tup)

Code

In [252]:
import numpy as np 
  
# input array 
in_arr1 = np.array(( 1, 2, 3 )) 
print ("1st Input array : \n", in_arr1)  
  
in_arr2 = np.array(( 4, 5, 6 )) 
print ("2nd Input array : \n", in_arr2)  
  
# Stacking the two arrays  
out_arr = np.column_stack((in_arr1, in_arr2)) 
print ("Output stacked array:\n ", out_arr) 

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output stacked array:
  [[1 4]
 [2 5]
 [3 6]]
